create table if not exists public.assessment_requests (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  phone text not null,
  child_age text not null,
  concern text not null,
  created_at timestamptz not null default now()
);

alter table public.assessment_requests enable row level security;

create policy "Allow public assessment requests"
on public.assessment_requests
for insert
to anon
with check (true);

revoke all on table public.assessment_requests from anon;
grant insert on table public.assessment_requests to anon;
